# COCO Classes
classes = {
    "BG": {
        "id": 0,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "person": {
        "id": 1,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "bicycle": {
        "id": 2,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "car": {
        "id": 3,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "motorcycle": {
        "id": 4,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "airplane": {
        "id": 5,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "bus": {
        "id": 6,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "train": {
        "id": 7,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "truck": {
        "id": 8,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "boat": {
        "id": 9,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "traffic light": {
        "id": 10,
        "type": "stationary",
        "mean_width": 2,
        "mean_height": 0.5,
    },
    "fire hydrant": {
        "id": 11,
        "type": "stationary",
        "mean_width": 0.5,
        "mean_height": 1,
    },
    "stop sign": {
        "id": 12,
        "type": "stationary",
        "mean_width": 0.8,
        "mean_height": 0.8,
    },
    "parking meter": {
        "id": 13,
        "type": "stationary",
        "mean_width": 0.3,
        "mean_height": 0.5,
    },
    "bench": {
        "id": 14,
        "type": "stationary",
        "mean_width": 2,
        "mean_height": 1,
    },
    "bird": {
        "id": 15,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "cat": {
        "id": 16,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "dog": {
        "id": 17,
        "type": "mobile",
        "mean_width": None,
        "mean_height": None,
    },
    "horse": {
        "id": 18,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "sheep": {
        "id": 19,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "cow": {
        "id": 20,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "elephant": {
        "id": 21,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "bear": {
        "id": 22,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "zebra": {
        "id": 23,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "giraffe": {
        "id": 24,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "backpack": {
        "id": 25,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "umbrella": {
        "id": 26,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "handbag": {
        "id": 27,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "tie": {
        "id": 28,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "suitcase": {
        "id": 29,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "frisbee": {
        "id": 30,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "skis": {
        "id": 31,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "snowboard": {
        "id": 32,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "sports ball": {
        "id": 33,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "kite": {
        "id": 34,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "baseball bat": {
        "id": 35,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "baseball glove": {
        "id": 36,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "skateboard": {
        "id": 37,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "surfboard": {
        "id": 38,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "tennis racket": {
        "id": 39,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "bottle": {
        "id": 40,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "wine glass": {
        "id": 41,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "cup": {
        "id": 42,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "fork": {
        "id": 43,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "knife": {
        "id": 44,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "spoon": {
        "id": 45,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "bowl": {
        "id": 46,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "banana": {
        "id": 47,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "apple": {
        "id": 48,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "sandwich": {
        "id": 49,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "orange": {
        "id": 50,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "broccoli": {
        "id": 51,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "carrot": {
        "id": 52,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "hot dog": {
        "id": 53,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "pizza": {
        "id": 54,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "donut": {
        "id": 55,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "cake": {
        "id": 56,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "chair": {
        "id": 57,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "couch": {
        "id": 58,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "potted plant": {
        "id": 59,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "bed": {
        "id": 60,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "dining table": {
        "id": 61,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "toilet": {
        "id": 62,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "tv": {
        "id": 63,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "laptop": {
        "id": 64,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "mouse": {
        "id": 65,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "remote": {
        "id": 66,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "keyboard": {
        "id": 67,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "cell phone": {
        "id": 68,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "microwave": {
        "id": 69,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "oven": {
        "id": 70,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "toaster": {
        "id": 71,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "sink": {
        "id": 72,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "refrigerator": {
        "id": 73,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "book": {
        "id": 74,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "clock": {
        "id": 75,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "vase": {
        "id": 76,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "scissors": {
        "id": 77,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "teddy bear": {
        "id": 78,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "hair drier": {
        "id": 79,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "toothbrush": {
        "id": 80,
        "type": "irrelevant",
        "mean_width": None,
        "mean_height": None,
    },
    "tree": {
        "id": 100,
        "type": "stationary",
        "mean_width": 1,
        "mean_height": 2,
    },
}

# class ID to class name lookup
class_lookup = {
    class_info["id"]: class_name
    for class_name, class_info in classes.items()
}
